SELECT AVG(q1.nb)
FROM  (SELECT pub.PUBLICATION_SERIES_ID, count(pub.PUBLICATION_SERIES_ID) as nb
      FROM PUBLICATIONS pub
      WHERE pub.PUBLICATION_SERIES_ID IS NOT NULL
      GROUP BY pub.PUBLICATION_SERIES_ID) q1